### ISSUE TITLE
Unable to turn off

### ISSUE THREAD

**Issue by ToddGreenfield** [kyleaa/homebridge-samsungtv2016#11]
Installed the plugin, works well to turn TV on, but does not turn off. (Defaulted to a Switch in Home app)
Snip of Syslog when attempting to turn off from an on state-

Dec 31 11:33:26 homepi homebridge[21821]: [12/31/2016, 11:33:26 AM] [Bedroom TV] received on command: 0
Dec 31 11:33:26 homepi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Dec 31 11:34:56 2016 [try http://www.rsyslog.com/e/2007 ]
Dec 31 11:33:26 homepi homebridge[21821]: [12/31/2016, 11:33:26 AM] [Bedroom TV] sending power key
Dec 31 11:33:26 homepi homebridge[21821]: [12/31/2016, 11:33:26 AM] [Bedroom TV] successfully powered off tv

I am not sure how to debug/investigate the "action 17 suspended) line...

Partial dump from "http://192.168.1.124:8001/api/v2/" in browser-
  "name": "[TV] Samsung 6 Series (50)",
  "version": "2.1.0",
  "type": "Samsung SmartTV",
      "model": "16_JAZZL_UHD_BASIC",
    "modelName": "UN50KU6300",
    "description": "Samsung DTV RCR",
    "networkType": "wireless",
      "firmwareVersion": "Unknown",
    "name": "[TV] Samsung 6 Series (50)",
     "OS": "Tizen"
  
 "type": "Samsung SmartTV",
  "uri": "http://192.168.1.124:8001/api/v2/",
  "remote": "1.0",
  "isSupport": "{\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"false\",\"DMP_available\":\"true\",\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"EDEN_available\":\"true\"}"
}

Suggestions? Thanks for any help.

**Comment by bspradling** [comment]
Running into this, too. My TV asks if I want to allow homebridge to control my TV but then upon asking Siri to turn off my TV, it doesn't do anything even though homebridge logs that it has been turned off successfully. Have you seem to be able to get it to work?

**Comment by ToddGreenfield** [comment]
I have not had a chance to mess with anything yet. I would love to have power and volume through the TV and also be able to control channel via DirecTV.

**Comment by bspradling** [comment]
I would too, switching inputs as well. I looked into it a little bit and it looks like Samsung made a change to their API. I really wish they would open this api to the public

**Comment by pedroserano** [comment]
This didn't used to be an issue for me. Now the off command doesn't work. The only thing that has changed (thanks super stable raspberry pi 3!) was the Samsung TV auto updated the software version. The only conclusion I can draw is that the updated API from Samsung threw a wrench in the off command. (It still works to turn on). I've learned my lesson and turned off the auto update on the TV but yeah need to figure out what the new off command is.

**Comment by pedroserano** [comment]
Raspberry pi 3*
The*

**Comment by kyleaa** [comment]
It looks like the tv became pickier about closing the websocket immediately after sending the power off packet - I put a delay on the websocket close and it seems to be working again, can you try now?

**Comment by kyleaa** [comment]
(published to npm as 0.0.6)

**Comment by ToddGreenfield** [comment]
using 0.0.6- 
So I first had the error situation noted below in 2nd para, and when I went to document findings everything seemed to work ok as such- TV turned on fine on first attempt (although it made a "bong" like another command was sent after 10s), but nothing on screen and it stayed on. I waited for about a minute then tried to turn off, TV turned off.  Tried to turn on again after 1m, and it turned on fine, again with the "bong". Off, on, off, on, all ok...

However, after a restart of homebridge- (this was duplicated 2x, but attempted a few - seemed intermittent)
Turned TV on ok, but then didn't turn off (homekit said TV was still on), then clicked off and TV turned on (but now out of sync with homekit IOS app). Clicked again (to turn on app/turn TV off and IOS showed an "!", eventually saw errors in the log and homebridge crashed/restarted... (IP 192.168.1.124 is my TV)

Jan  7 08:12:21 homepi homebridge[18506]: [1/7/2017, 8:12:21 AM] [Ecobee] [Upstairs] Occupied | 34% | 18.5°C
Jan  7 08:12:21 homepi homebridge[18506]: [1/7/2017, 8:12:21 AM] [Ecobee] Wait | 30 seconds
Jan  7 08:12:21 homepi homebridge[18506]: [1/7/2017, 8:12:21 AM] [Bedroom TV] received on command: 0
Jan  7 08:12:21 homepi homebridge[18506]: [1/7/2017, 8:12:21 AM] [Bedroom TV] sending power key
Jan  7 08:12:44 homepi homebridge[18506]: events.js:160
Jan  7 08:12:44 homepi homebridge[18506]: throw er; // Unhandled 'error' event
Jan  7 08:12:44 homepi homebridge[18506]: ^
Jan  7 08:12:44 homepi homebridge[18506]: Error: connect ETIMEDOUT 192.168.1.124:8001
Jan  7 08:12:44 homepi homebridge[18506]: at Object.exports._errnoException (util.js:1022:11)
Jan  7 08:12:44 homepi homebridge[18506]: at exports._exceptionWithHostPort (util.js:1045:20)
Jan  7 08:12:44 homepi homebridge[18506]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
Jan  7 08:12:44 homepi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jan  7 08:12:44 homepi systemd[1]: Unit homebridge.service entered failed state.
Jan  7 08:12:54 homepi systemd[1]: homebridge.service holdoff time over, scheduling restart.
Jan  7 08:12:54 homepi systemd[1]: Stopping Node.js HomeKit Server...
Jan  7 08:12:54 homepi systemd[1]: Starting Node.js HomeKit Server...
Jan  7 08:12:54 homepi systemd[1]: Started Node.js HomeKit Server.

**Comment by inzlabs** [comment]
Hi Kyle, first of all, thank you for your hard and kind work. Thank you for your time on this, that make us enjoy better our homes.

This is the log after updating, I am glad to report that works over the home app and Siri.

> [1/7/2017, 5:09:08 PM] Homebridge is running on port 51826.
> [1/7/2017, 5:10:59 PM] [TV Living room] No response from TV
> [1/7/2017, 5:11:01 PM] [TV Living room] received on command: 1
> [1/7/2017, 5:11:03 PM] [TV Living room] No response from TV
> [1/7/2017, 5:11:03 PM] [TV Living room] attempting wake
> [1/7/2017, 5:11:03 PM] [TV Living room] successfully woke tv
> [1/7/2017, 5:12:28 PM] [TV Living room] received on command: false
> [1/7/2017, 5:12:28 PM] [TV Living room] sending power key
> [1/7/2017, 5:12:28 PM] [TV Living room] websocket connect
> [1/7/2017, 5:12:28 PM] [TV Living room] successfully powered off tv
> [1/7/2017, 5:12:29 PM] [TV Living room] websocket closed
> [1/7/2017, 5:12:58 PM] [TV Living room] received on command: true
> [1/7/2017, 5:13:00 PM] [TV Living room] No response from TV
> [1/7/2017, 5:13:00 PM] [TV Living room] attempting wake
> [1/7/2017, 5:13:00 PM] [TV Living room] successfully woke tv

I did not try to replicate Todd's scenario -I'm new on this raspberry, terminal thingy- so I don't know how to restart an app, sadly I reboot the whole raspberry and I can tell no errors so far.

**Comment by pedroserano** [comment]
Yes, works for me now. Thank you!

**Comment by inzlabs** [comment]
I am sorry to be the one who brings bad news. I think I figure out one situation when the TV is turned off manually via remote control, the plugging can't turn it on back. Curiously the log and Siri says it was turned on, but nope.
```

[1/10/2017, 12:49:21 AM] [TV Living room] received on command: true
[1/10/2017, 12:49:23 AM] [TV Living room] No response from TV
[1/10/2017, 12:49:23 AM] [TV Living room] attempting wake
[1/10/2017, 12:49:24 AM] [TV Living room] successfully woke tv
[1/10/2017, 12:49:58 AM] [TV Living room] No response from TV
[1/10/2017, 12:50:01 AM] [TV Living room] received on command: 1
[1/10/2017, 12:50:03 AM] [TV Living room] No response from TV
[1/10/2017, 12:50:03 AM] [TV Living room] attempting wake
[1/10/2017, 12:50:03 AM] [TV Living room] successfully woke tv
[1/10/2017, 12:50:42 AM] [TV Living room] received on command: false
[1/10/2017, 12:50:42 AM] [TV Living room] sending power key
[1/10/2017, 12:50:43 AM] [TV Living room] websocket connect
[1/10/2017, 12:50:43 AM] [TV Living room] successfully powered off tv
[1/10/2017, 12:50:44 AM] [TV Living room] websocket closed

```

ps. I promise I am not crazy... :S
