### ISSUE TITLE
Compatibility with H, J and L series

### ISSUE THREAD

**Issue by achimhoth** [kyleaa/homebridge-samsungtv2016#13]
Do you know which TV models work with this code? I guess the K-Series is working fine but what about the other models like H, J and L?

**Comment by kyleaa** [comment]
H is a 2014 model and J/L are 2015. These should be covered by homebridge-samsungtv.

**Comment by nspinelli** [comment]
This does not work on JS9000

**Comment by kyleaa** [comment]
@nspinelli the J series is a 2015 model, this should not work with it.
