### ISSUE TITLE
How to does it work? and how does it work with Home Assistant?

### ISSUE THREAD

**Issue by bachoo786** [kyleaa/homebridge-samsungtv2016#16]
Hi

I have managed to install homebridge and was wondering how does this software work? What are the next steps involved? Also can this be integrated with homeassistant?

**Comment by kyleaa** [comment]
I'm not sure what you're asking about - Homebridge setup instructions are found at https://github.com/nfarina/homebridge

If you're asking about implementation details, it uses WebSockets to communicate with the TV. I am not familiar with homeassistant, but a quick search looks like it is written in Python. I presume a python developer could easily port the logic over.
