### ISSUE TITLE
More characteristics / services

### ISSUE THREAD

**Issue by ryck** [kyleaa/homebridge-samsungtv2016#2]
What else can we implement? Maybe volume?

**Comment by kyleaa** [comment]
I'm not aware of any way to get the volume, but we could certainly increment/decrement the volume.

**Comment by ryck** [comment]
That would me nice. Maybe mute too?

**Comment by kyleaa** [comment]
I took a look through https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js and I don't see any good way to implement these given that we don't have any way to read current state. I'm closing this for now but would welcome any PRs.
