### ISSUE TITLE
is this dead ?

### ISSUE THREAD

**Issue by KennyVB** [kyleaa/homebridge-samsungtv2016#23]
i see a fork of your GitHub which added mute, can't how ever make it work hehe
but never the less! it is possible to add functions somehow ?

**Comment by huglester** [comment]
Any idea, if this model: UE32J6302
is supposed to use this plugin? Because does not work, and I am not sure if I missed any steps

**Comment by kyleaa** [comment]
@huglester - See issue #13 - J series are a 2015 TV.
