### ISSUE TITLE
could not close the TV since latest firmware of KU6290 TV...

### ISSUE THREAD

**Issue by jsdecarie** [kyleaa/homebridge-samsungtv2016#24]
Title say it all..

after the last firmware update of the TV, I could not close the TV anymore... turn on without issue.

I do not think a firmware downgrade is a good idea on a TV, anyone is having the same issue ?

**Comment by Hackashaq666** [comment]
I am having problems now too, KU6290 TV with firmware 1206 and now 1207.
Can turn TV off, but not on.
Similar issue when using homeassistant.

**Comment by Hackashaq666** [comment]
If I manually send wake on lan to tv it turns on.

**Comment by Hackashaq666** [comment]
I determined the cause of my issue.
I am using nmap as people tracker in home-assistant.
The Npcap loopback network adapter was causing the problem.
Once I reconfigured Npcap, all is well.
